### ISSUE TITLE
CI: Replace 3.7-dev with 3.7

### ISSUE THREAD

**Issue by hugovk** [pylast/pylast#278]
`3.7-dev` is an early alpha. 

Replace it with the final 3.7 release on Travis CI.

**Comment by jacebrowning** [comment]
It's actually available right now on xenial: 

```
language: python
matrix:
    include:
        - python: 3.7
          dist: xenial
          sudo: true
```
